import React, { useState, useEffect, useMemo } from 'react';
import { 
  Project, 
  ProjectRationale, 
  ProjectCostEstimateItem, 
  ProjectActivityItem, 
  ProjectScheduleTask,
  ProjectROI,
  User 
} from '../types';
import { ProjectROICalculator } from './ProjectROICalculator';
import { JalaliDatePicker } from './JalaliDatePicker';
import { 
  getTodayJalali, 
  formatJalaliDate, 
  jalaliStringToJsDate, 
  toPersianDigits 
} from '../utils/jalali';
import { addDaysToJalaliDate, recalculateScheduleTasks } from '../utils/scheduleCalculations';
import { formatCurrency } from '../utils/evmCalculations';
import { 
  X, 
  Building2, 
  Plus, 
  Trash2, 
  DollarSign, 
  CheckCircle2, 
  User as UserIcon, 
  Briefcase, 
  Target, 
  Sparkles, 
  Calculator,
  ListTodo,
  SendHorizontal,
  Clock,
  AlertCircle,
  Loader2
} from 'lucide-react';
import confetti from 'canvas-confetti';

interface NewProjectModalProps {
  isOpen: boolean;
  onClose: () => void;
  projects: Project[];
  currentUser?: User;
  onSaveProject: (project: Omit<Project, 'id' | 'createdAt' | 'updatedAt'>) => void;
}

const RATIONALE_OPTIONS: { value: ProjectRationale; label: string; desc: string }[] = [
  { 
    value: 'جهت بهبود فرآیندها و سیستم‌ها', 
    label: 'جهت بهبود فرآیندها و سیستم‌ها', 
    desc: 'ارتقای زیرساخت‌ها، دیجیتال‌سازی و بازمهندسی روش‌های اجرایی' 
  },
  { 
    value: 'افزایش ظرفیت تولید یا خدمات', 
    label: 'افزایش ظرفیت تولید یا خدمات', 
    desc: 'توسعه خطوط، احداث تاسیسات جدید و پاسخ به تقاضای بازار' 
  },
  { 
    value: 'افزایش بهره‌وری و کاهش اتلاف', 
    label: 'افزایش بهره‌وری و کاهش اتلاف', 
    desc: 'کاهش هزینه‌های عملیاتی، صرفه‌جویی انرژی و بهینه‌سازی منابع' 
  },
  { 
    value: 'مصوبه جلسات هماهنگی سازمانی', 
    label: 'مصوبه جلسات هماهنگی سازمانی', 
    desc: 'تصمیمات کارگروه‌های تخصصی، کمیته‌های فنی و راهبری' 
  },
  { 
    value: 'مصوبه و تکلیف هیئت مدیره', 
    label: 'مصوبه و تکلیف هیئت مدیره', 
    desc: 'ابلاغ مستقیم هیئت مدیره و اهداف کلان راهبردی هلدینگ' 
  },
  { 
    value: 'الزامات قانونی و حاکمیتی', 
    label: 'الزامات قانونی و حاکمیتی', 
    desc: 'رعایت استانداردها، الزامات ایمنی و زیست‌محیطی (HSE)' 
  },
  { 
    value: 'سایر موارد', 
    label: 'سایر اهداف و موارد استراتژیک', 
    desc: 'تعریف بر اساس نیازهای خاص و اقتضایی سازمان' 
  },
];

const SUGGESTED_COST_TYPES = [
  'هزینه تجهیز کارگاه و مطالعات اولیه',
  'هزینه خرید زمین و تملک اراضی',
  'هزینه طراحی، مهندسی و نظارت کارگاهی',
  'تامین مصالح، آهن‌آلات و تجهیزات اصلی',
  'دستمزد پیمانکاران اجرایی و دست‌دوم',
  'خرید ماشین‌آلات، پمپ‌ها و تجهیزات مکانیکی/برقی',
  'هزینه نصب، تست و راه‌اندازی (Commissioning)',
  'هزینه‌های غیرمستقیم، اداری و بیمه',
  'ذخیره احتیاطی و ریسک (Contingency Reserve)',
];

export const NewProjectModal: React.FC<NewProjectModalProps> = ({
  isOpen,
  onClose,
  projects,
  currentUser,
  onSaveProject,
}) => {
  // Generate Next Project Code automatically based on existing projects
  const autoGeneratedCode = useMemo(() => {
    if (!projects || projects.length === 0) return 'PRJ-2026-01';
    
    let maxSeq = 0;
    let yearPrefix = '2026';
    
    projects.forEach((p) => {
      if (!p.code) return;
      const match = p.code.match(/PRJ-(?:(\d{4})-)?(\d+)/i);
      if (match) {
        if (match[1]) yearPrefix = match[1];
        const num = parseInt(match[2], 10);
        if (!isNaN(num) && num > maxSeq) {
          maxSeq = num;
        }
      }
    });

    const nextSeq = maxSeq + 1;
    const formattedSeq = nextSeq < 10 ? `0${nextSeq}` : `${nextSeq}`;
    return `PRJ-${yearPrefix}-${formattedSeq}`;
  }, [projects]);

  // Today Jalali
  const todayFormatted = useMemo(() => {
    const [jy, jm, jd] = getTodayJalali();
    return formatJalaliDate(jy, jm, jd, true);
  }, []);

  // Section 1: Requester Info
  const [requesterName, setRequesterName] = useState<string>('');
  const [requesterUnit, setRequesterUnit] = useState<string>('');
  const [requestDate, setRequestDate] = useState<string>('۱۴۰۳/۰۶/۰۱');

  // Section 2: Project Rationale
  const [rationale, setRationale] = useState<ProjectRationale>('جهت بهبود فرآیندها و سیستم‌ها');
  const [customRationaleDetails, setCustomRationaleDetails] = useState<string>('');

  // Section 3: Project Main Details & Baseline Dates
  const [code, setCode] = useState<string>('');
  const [name, setName] = useState<string>('');
  const [responsibleUnit, setResponsibleUnit] = useState<string>('واحد فنی و مهندسی');
  const [managerName, setManagerName] = useState<string>('');
  const [category, setCategory] = useState<string>('ابنیه و ساختمانی');
  const [baselineStartDate, setBaselineStartDate] = useState<string>('۱۴۰۳/۰۶/۰۱');
  const [baselineFinishDate, setBaselineFinishDate] = useState<string>('۱۴۰۴/۰۶/۳۱');
  const [description, setDescription] = useState<string>('');

  // Section 4: Cost Breakdown (برآورد هزینه‌ها)
  const [costItems, setCostItems] = useState<ProjectCostEstimateItem[]>([
    { id: '1', costType: 'هزینه طراحی، مهندسی و نظارت', estimatedAmount: 2500, description: 'تهیه نقشه‌های فاز ۱ و ۲ و خدمات مشاوره' },
    { id: '2', costType: 'تامین مصالح و تجهیزات اصلی', estimatedAmount: 18000, description: 'خرید آهن‌آلات، میلگرد، لوله‌ها و تجهیزات فرآیندی' },
    { id: '3', costType: 'دستمزد عملیات اجرایی و پیمانکاران', estimatedAmount: 9500, description: 'عملیات خاکی، بتن‌ریزی، نصب و لوله‌کشی' },
  ]);

  // Section 5: Activities & Duration (فعالیت‌ها و مدت زمان)
  const [activityItems, setActivityItems] = useState<ProjectActivityItem[]>([
    { id: '1', activityName: 'مطالعات ژئوتکنیک و تهیه نقشه‌های اجرایی فاز ۲', durationDays: 45, responsiblePerson: 'واحد مهندسی مشاور' },
    { id: '2', activityName: 'تجهیز کارگاه، گودبرداری و اجرای فونداسیون', durationDays: 90, responsiblePerson: 'پیمانکار عمومی ابنیه' },
    { id: '3', activityName: 'تامین و تحویل اقلام کلیدی (Long Lead Items)', durationDays: 120, responsiblePerson: 'واحد بازرگانی و تدارکات' },
    { id: '4', activityName: 'عملیات نصب تجهیزات و اجرای خطوط پایپینگ', durationDays: 110, responsiblePerson: 'تیم مکانیک و نصب' },
  ]);

  // Section 4.5: ROI & Financial Feasibility (امکان‌سنجی اقتصادی و نرخ بازگشت سرمایه)
  const [projectROI, setProjectROI] = useState<ProjectROI | undefined>(undefined);

  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);

  // Auto-fill values when modal opens
  useEffect(() => {
    if (isOpen) {
      setCode(autoGeneratedCode);
      if (currentUser) {
        setRequesterName((prev) => prev.trim() ? prev : (currentUser.fullName || ''));
        setRequesterUnit((prev) => prev.trim() ? prev : (currentUser.department || 'واحد مدیریت پروژه و PMO'));
        setManagerName((prev) => prev.trim() ? prev : (currentUser.fullName || 'مهندس ناظر پروژه'));
      } else {
        setManagerName((prev) => prev.trim() ? prev : 'مهندس ناظر پروژه');
      }
      setRequestDate(todayFormatted);
      setErrors({});
      setIsSubmitting(false);
    }
  }, [isOpen, autoGeneratedCode, currentUser, todayFormatted]);

  // Calculate Project Duration in Days based on baseline start and finish dates
  const calculatedProjectDurationDays = useMemo(() => {
    const startDate = jalaliStringToJsDate(baselineStartDate);
    const finishDate = jalaliStringToJsDate(baselineFinishDate);
    if (startDate && finishDate) {
      const diffTime = finishDate.getTime() - startDate.getTime();
      const days = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
      return days > 0 ? days : 0;
    }
    return 0;
  }, [baselineStartDate, baselineFinishDate]);

  // Calculate Total Estimated Budget (BAC)
  const totalBudgetBAC = useMemo(() => {
    return costItems.reduce((acc, item) => acc + (Number(item.estimatedAmount) || 0), 0);
  }, [costItems]);

  // Add Cost Item Handler
  const handleAddCostItem = () => {
    const newItem: ProjectCostEstimateItem = {
      id: Date.now().toString(),
      costType: SUGGESTED_COST_TYPES[costItems.length % SUGGESTED_COST_TYPES.length] || 'سایر هزینه‌های مستقیم پروژه',
      estimatedAmount: 1000,
      description: '',
    };
    setCostItems([...costItems, newItem]);
  };

  // Remove Cost Item Handler
  const handleRemoveCostItem = (id: string) => {
    if (costItems.length === 1) {
      alert('حداقل یک ردیف برآورد هزینه باید وجود داشته باشد.');
      return;
    }
    setCostItems(costItems.filter((c) => c.id !== id));
  };

  // Update Cost Item Handler
  const handleUpdateCostItem = (id: string, field: keyof ProjectCostEstimateItem, value: any) => {
    setCostItems(
      costItems.map((c) => (c.id === id ? { ...c, [field]: value } : c))
    );
  };

  // Add Activity Item Handler
  const handleAddActivityItem = () => {
    const newItem: ProjectActivityItem = {
      id: Date.now().toString(),
      activityName: `فعالیت مرحله‌ای ${activityItems.length + 1}`,
      durationDays: 30,
      responsiblePerson: managerName || 'سرپرست کارگاه',
    };
    setActivityItems([...activityItems, newItem]);
  };

  // Remove Activity Item Handler
  const handleRemoveActivityItem = (id: string) => {
    if (activityItems.length === 1) {
      alert('حداقل یک فعالیت باید برای پروژه ثبت شود.');
      return;
    }
    setActivityItems(activityItems.filter((a) => a.id !== id));
  };

  // Update Activity Item Handler
  const handleUpdateActivityItem = (id: string, field: keyof ProjectActivityItem, value: any) => {
    setActivityItems(
      activityItems.map((a) => (a.id === id ? { ...a, [field]: value } : a))
    );
  };

  // Submit Handler
  const handleSubmit = (e?: React.FormEvent) => {
    if (e) {
      e.preventDefault();
      e.stopPropagation();
    }
    if (isSubmitting) return;

    const errs: Record<string, string> = {};

    if (!requesterName.trim()) errs.requesterName = 'نام درخواست‌کننده الزامی است.';
    if (!requesterUnit.trim()) errs.requesterUnit = 'واحد درخواست‌کننده الزامی است.';
    if (!name.trim()) errs.name = 'نام کامل پروژه الزامی است.';
    if (!code.trim()) errs.code = 'کد پروژه الزامی است.';
    if (!responsibleUnit.trim()) errs.responsibleUnit = 'واحد مسئول پروژه الزامی است.';
    if (!managerName.trim()) errs.managerName = 'نام مدیر پروژه الزامی است.';
    if (totalBudgetBAC <= 0) errs.budgetBAC = 'جمع کل برآورد بودجه باید بزرگتر از صفر باشد.';

    if (Object.keys(errs).length > 0) {
      setErrors(errs);
      
      // Auto-scroll and focus the first invalid field
      const firstKey = Object.keys(errs)[0];
      const targetElement = document.getElementById(`field-${firstKey}`);
      if (targetElement) {
        targetElement.scrollIntoView({ behavior: 'smooth', block: 'center' });
        setTimeout(() => {
          targetElement.focus();
        }, 150);
      }
      return;
    }

    setIsSubmitting(true);

    // Generate initial schedule tasks with finish-to-start dependencies
    let initialScheduleTasks: ProjectScheduleTask[] = [];
    if (activityItems.length > 0) {
      let currentStart = baselineStartDate;
      activityItems.forEach((act, idx) => {
        const dur = Math.max(1, act.durationDays || 7);
        const fin = addDaysToJalaliDate(currentStart, dur - 1);
        const prevTask = idx > 0 ? initialScheduleTasks[idx - 1] : null;

        initialScheduleTasks.push({
          id: `task-gen-${Date.now()}-${idx + 1}`,
          wbs: `${idx + 1}`,
          name: act.activityName.trim() || `فعالیت مرحله ${idx + 1}`,
          level: 0,
          startDate: currentStart,
          finishDate: fin,
          durationDays: dur,
          predecessorId: prevTask ? prevTask.id : undefined,
          responsiblePerson: act.responsiblePerson.trim() || managerName,
          progressPct: 0,
        });

        // Next task starts the day after this task finishes
        currentStart = addDaysToJalaliDate(fin, 1);
      });
      initialScheduleTasks = recalculateScheduleTasks(initialScheduleTasks);
    } else {
      initialScheduleTasks = [
        {
          id: `task-gen-${Date.now()}-1`,
          wbs: '1',
          name: `فاز آغازین و برنامه‌ریزی پروژه ${name}`,
          level: 0,
          startDate: baselineStartDate,
          finishDate: baselineFinishDate,
          durationDays: Math.max(1, calculatedProjectDurationDays),
          progressPct: 0,
          responsiblePerson: managerName,
        }
      ];
    }

    onSaveProject({
      code,
      name,
      description: description.trim() || `پروژه ${name} مصوب واحد ${responsibleUnit}`,
      managerName,
      responsibleUnit,
      requesterName,
      requesterUnit,
      requestDate,
      rationale: customRationaleDetails ? `${rationale} (${customRationaleDetails})` : rationale,
      baselineStartDate,
      baselineFinishDate,
      durationDays: calculatedProjectDurationDays,
      
      // Initial Status: In Queue for CEO Approval
      status: 'pending_ceo',
      charterStatus: 'در انتظار تایید مدیرعامل',
      ganttStatus: 'در حال تهیه',
      ceoApprovalStatus: 'pending',

      costEstimates: costItems,
      budgetBAC: totalBudgetBAC,
      roi: projectROI,
      activities: activityItems,
      scheduleTasks: initialScheduleTasks,
      category,
    });

    confetti({
      particleCount: 50,
      spread: 60,
      origin: { y: 0.6 },
    });

    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-3 sm:p-5 overflow-y-auto">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-3xl max-w-4xl w-full shadow-2xl overflow-hidden my-4 flex flex-col text-right max-h-[94vh]">
        
        {/* Header */}
        <div className="p-5 border-b border-slate-200 dark:border-slate-800 bg-gradient-to-l from-indigo-50/80 via-white to-slate-50 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-3 rounded-2xl bg-indigo-600 text-white shadow-md shadow-indigo-600/20">
              <Building2 className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-base sm:text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
                <span>فرم تعریف پروژه جدید</span>
                <span className="font-mono text-xs px-2.5 py-0.5 rounded-full bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 border border-indigo-200 dark:border-indigo-800">
                  {code || autoGeneratedCode}
                </span>
              </h2>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-slate-700 dark:hover:text-white hover:bg-slate-100 dark:hover:bg-slate-800 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Scrollable Form Body */}
        <form onSubmit={handleSubmit} className="p-5 sm:p-7 space-y-6 overflow-y-auto flex-1">
          
          {/* ========================================================================= */}
          {/* بخش ۱: اطلاعات درخواست کننده (قسمت اول) */}
          {/* ========================================================================= */}
          <div className="p-4 sm:p-5 rounded-2xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800/80 space-y-3.5">
            <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-bold text-xs sm:text-sm border-b border-slate-200/80 dark:border-slate-800 pb-2">
              <UserIcon className="w-4 h-4" />
              <span>بخش اول: اطلاعات متقاضی و درخواست‌کننده پروژه</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              {/* نام درخواست کننده */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
                  نام درخواست‌کننده <span className="text-rose-500">*</span>
                </label>
                <input
                  id="field-requesterName"
                  type="text"
                  value={requesterName}
                  onChange={(e) => {
                    setRequesterName(e.target.value);
                    if (errors.requesterName) setErrors((prev) => ({ ...prev, requesterName: '' }));
                  }}
                  placeholder="مثال: مهندس احمدی"
                  className={`w-full bg-white dark:bg-slate-900 border rounded-xl px-3 py-2 text-xs text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                    errors.requesterName
                      ? 'border-rose-500 ring-2 ring-rose-500/20 bg-rose-50/20 dark:bg-rose-950/20'
                      : 'border-slate-300 dark:border-slate-700'
                  }`}
                />
                {errors.requesterName && <p className="text-rose-500 text-[10px] mt-1 font-semibold">{errors.requesterName}</p>}
              </div>

              {/* واحد درخواست کننده */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
                  واحد درخواست‌کننده <span className="text-rose-500">*</span>
                </label>
                <input
                  id="field-requesterUnit"
                  type="text"
                  value={requesterUnit}
                  onChange={(e) => {
                    setRequesterUnit(e.target.value);
                    if (errors.requesterUnit) setErrors((prev) => ({ ...prev, requesterUnit: '' }));
                  }}
                  placeholder="مثال: معاونت توسعه و بهره‌برداری"
                  className={`w-full bg-white dark:bg-slate-900 border rounded-xl px-3 py-2 text-xs text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                    errors.requesterUnit
                      ? 'border-rose-500 ring-2 ring-rose-500/20 bg-rose-50/20 dark:bg-rose-950/20'
                      : 'border-slate-300 dark:border-slate-700'
                  }`}
                />
                {errors.requesterUnit && <p className="text-rose-500 text-[10px] mt-1 font-semibold">{errors.requesterUnit}</p>}
              </div>

              {/* تاریخ درخواست */}
              <div>
                <JalaliDatePicker
                  label="تاریخ درخواست"
                  value={requestDate}
                  onChange={setRequestDate}
                  placeholder="۱۴۰۳/۰۶/۰۱"
                />
              </div>
            </div>
          </div>

          {/* ========================================================================= */}
          {/* بخش ۲: علت و انگیزه تعریف پروژه (قسمت دوم) */}
          {/* ========================================================================= */}
          <div className="p-4 sm:p-5 rounded-2xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800/80 space-y-3.5">
            <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-bold text-xs sm:text-sm border-b border-slate-200/80 dark:border-slate-800 pb-2">
              <Target className="w-4 h-4" />
              <span>بخش دوم: علت و انگیزه تعریف پروژه</span>
            </div>

            <div className="space-y-3">
              <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                دسته‌بندی ضرورت و هدف ایجاد پروژه <span className="text-rose-500">*</span>
              </label>

              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2.5">
                {RATIONALE_OPTIONS.map((opt) => (
                  <button
                    key={opt.value}
                    type="button"
                    onClick={() => setRationale(opt.value)}
                    className={`p-3 rounded-xl border text-right transition cursor-pointer flex items-center justify-between ${
                      rationale === opt.value
                        ? 'bg-indigo-50/90 dark:bg-indigo-950/60 border-indigo-500 text-indigo-900 dark:text-indigo-200 ring-2 ring-indigo-500/20'
                        : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300 hover:border-slate-300 dark:hover:border-slate-700'
                    }`}
                  >
                    <span className="text-xs font-bold">{opt.label}</span>
                    {rationale === opt.value && <CheckCircle2 className="w-4 h-4 text-indigo-600 dark:text-indigo-400 shrink-0" />}
                  </button>
                ))}
              </div>

              {/* توضیحات تکمیلی توجیه پروژه */}
              <div className="pt-1">
                <input
                  type="text"
                  value={customRationaleDetails}
                  onChange={(e) => setCustomRationaleDetails(e.target.value)}
                  placeholder="توضیحات تکمیلی علت تعریف یا شماره صورتجلسه/مصوبه هیئت مدیره (اختیاری)..."
                  className="w-full bg-white dark:bg-slate-900 border border-slate-300 dark:border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
                />
              </div>
            </div>
          </div>

          {/* ========================================================================= */}
          {/* بخش ۳: مشخصات کامل، کد خودکار، مدیر و زمان‌بندی مبنا (قسمت سوم) */}
          {/* ========================================================================= */}
          <div className="p-4 sm:p-5 rounded-2xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800/80 space-y-4">
            <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-bold text-xs sm:text-sm border-b border-slate-200/80 dark:border-slate-800 pb-2">
              <Briefcase className="w-4 h-4" />
              <span>بخش سوم: مشخصات اصلی پروژه، متولیان و خطوط مبنای زمانی</span>
            </div>

            {/* نام و کد پروژه */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="sm:col-span-2">
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
                  نام کامل پروژه <span className="text-rose-500">*</span>
                </label>
                <input
                  id="field-name"
                  type="text"
                  value={name}
                  onChange={(e) => {
                    setName(e.target.value);
                    if (errors.name) setErrors((prev) => ({ ...prev, name: '' }));
                  }}
                  placeholder=""
                  className={`w-full bg-white dark:bg-slate-900 border rounded-xl px-3 py-2 text-xs text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 font-medium ${
                    errors.name
                      ? 'border-rose-500 ring-2 ring-rose-500/20 bg-rose-50/20 dark:bg-rose-950/20'
                      : 'border-slate-300 dark:border-slate-700'
                  }`}
                />
                {errors.name && <p className="text-rose-500 text-[10px] mt-1 font-semibold">{errors.name}</p>}
              </div>

              {/* کد پروژه - خودکار */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
                  کد پروژه (تولید خودکار بر اساس آخرین کد) <span className="text-rose-500">*</span>
                </label>
                <div className="relative">
                  <input
                    id="field-code"
                    type="text"
                    value={code}
                    onChange={(e) => {
                      setCode(e.target.value);
                      if (errors.code) setErrors((prev) => ({ ...prev, code: '' }));
                    }}
                    placeholder="PRJ-2026-06"
                    className={`w-full bg-slate-100 dark:bg-slate-800 border rounded-xl px-3 py-2 text-xs text-indigo-600 dark:text-indigo-400 font-mono text-left font-bold focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                      errors.code
                        ? 'border-rose-500 ring-2 ring-rose-500/20 bg-rose-50/20 dark:bg-rose-950/20'
                        : 'border-slate-300 dark:border-slate-700'
                    }`}
                  />
                  <Sparkles className="w-4 h-4 text-indigo-500 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none opacity-60" />
                </div>
                {errors.code && <p className="text-rose-500 text-[10px] mt-1 font-semibold">{errors.code}</p>}
              </div>
            </div>

            {/* واحد مسئول و مدیر پروژه */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
                  واحد مسئول پروژه <span className="text-rose-500">*</span>
                </label>
                <input
                  id="field-responsibleUnit"
                  type="text"
                  value={responsibleUnit}
                  onChange={(e) => {
                    setResponsibleUnit(e.target.value);
                    if (errors.responsibleUnit) setErrors((prev) => ({ ...prev, responsibleUnit: '' }));
                  }}
                  placeholder="مثال: واحد فنی و مهندسی خطوط لوله"
                  className={`w-full bg-white dark:bg-slate-900 border rounded-xl px-3 py-2 text-xs text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                    errors.responsibleUnit
                      ? 'border-rose-500 ring-2 ring-rose-500/20 bg-rose-50/20 dark:bg-rose-950/20'
                      : 'border-slate-300 dark:border-slate-700'
                  }`}
                />
                {errors.responsibleUnit && <p className="text-rose-500 text-[10px] mt-1 font-semibold">{errors.responsibleUnit}</p>}
              </div>

              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300">
                    مدیر پروژه <span className="text-rose-500">*</span>
                  </label>
                  {currentUser?.fullName && managerName !== currentUser.fullName && (
                    <button
                      type="button"
                      onClick={() => {
                        setManagerName(currentUser.fullName);
                        if (errors.managerName) setErrors((prev) => ({ ...prev, managerName: '' }));
                      }}
                      className="text-[10px] text-indigo-600 dark:text-indigo-400 hover:underline cursor-pointer"
                    >
                      (تنظیم به نام من)
                    </button>
                  )}
                </div>
                <input
                  id="field-managerName"
                  type="text"
                  value={managerName}
                  onChange={(e) => {
                    setManagerName(e.target.value);
                    if (errors.managerName) setErrors((prev) => ({ ...prev, managerName: '' }));
                  }}
                  placeholder="نام و نام خانوادگی مدیر پروژه"
                  className={`w-full bg-white dark:bg-slate-900 border rounded-xl px-3 py-2 text-xs text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 ${
                    errors.managerName
                      ? 'border-rose-500 ring-2 ring-rose-500/20 bg-rose-50/20 dark:bg-rose-950/20'
                      : 'border-slate-300 dark:border-slate-700'
                  }`}
                />
                {errors.managerName && <p className="text-rose-500 text-[10px] mt-1 font-semibold">{errors.managerName}</p>}
              </div>

              {/* دسته بندی حوزه پروژه */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
                  دسته‌بندی و حوزه فنی
                </label>
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value)}
                  className="w-full bg-white dark:bg-slate-900 border border-slate-300 dark:border-slate-700 rounded-xl px-3 py-2 text-xs text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-indigo-500 cursor-pointer font-medium"
                >
                  <option value="ابنیه و ساختمانی">ابنیه و ساختمانی</option>
                  <option value="تاسیسات و مکانیک">تاسیسات و مکانیک</option>
                  <option value="خطوط لوله و نفت/گاز">خطوط لوله و نفت/گاز</option>
                  <option value="برق و ابزار دقیق">برق و ابزار دقیق</option>
                  <option value="فناوری اطلاعات و تحول دیجیتال">فناوری اطلاعات و تحول دیجیتال</option>
                  <option value="HSE و محیط زیست">HSE و محیط زیست</option>
                </select>
              </div>
            </div>

            {/* تاریخ‌های برنامه‌ریزی شده و مدت زمان محاسبه‌شده */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-1">
              <div>
                <JalaliDatePicker
                  label="تاریخ شروع برنامه‌ریزی شده (مبنا)"
                  value={baselineStartDate}
                  onChange={setBaselineStartDate}
                  placeholder="۱۴۰۳/۰۶/۰۱"
                />
              </div>

              <div>
                <JalaliDatePicker
                  label="تاریخ پایان برنامه‌ریزی شده (مبنا)"
                  value={baselineFinishDate}
                  onChange={setBaselineFinishDate}
                  placeholder="۱۴۰۴/۰۶/۳۱"
                />
              </div>

              {/* مدت زمان کل پروژه (محاسبه خودکار) */}
              <div>
                <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
                  مدت زمان پروژه (محاسبه خودکار)
                </label>
                <div className="flex items-center justify-between bg-white dark:bg-slate-900 border border-slate-300 dark:border-slate-700 rounded-xl px-3 py-2 text-xs">
                  <span className="text-slate-500 dark:text-slate-400">مدت تقویمی:</span>
                  <span className="font-bold font-mono text-indigo-600 dark:text-indigo-400 text-sm">
                    {toPersianDigits(calculatedProjectDurationDays)} روز
                  </span>
                </div>
              </div>
            </div>

            {/* شرح و اهداف کلان */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1.5">
                شرح اهداف و محدوده کاری پروژه
              </label>
              <textarea
                rows={2}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="توضیح خلاصه پیرامون شرح خدمات، خروجی‌های مورد انتظار و مشخصات فنی پروژه..."
                className="w-full bg-white dark:bg-slate-900 border border-slate-300 dark:border-slate-700 rounded-xl p-3 text-xs text-slate-900 dark:text-white placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500"
              />
            </div>
          </div>

          {/* ========================================================================= */}
          {/* بخش ۴: برآورد هزینه‌ها و جمع نهایی بودجه BAC (قسمت چهارم) */}
          {/* ========================================================================= */}
          <div className="p-4 sm:p-5 rounded-2xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800/80 space-y-4">
            <div className="flex items-center justify-between border-b border-slate-200/80 dark:border-slate-800 pb-2">
              <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-bold text-xs sm:text-sm">
                <Calculator className="w-4 h-4" />
                <span>بخش چهارم: برآورد تفکیکی هزینه‌ها و بودجه‌بندی</span>
              </div>

              {/* دکمه مثبت افزودن هزینه */}
              <button
                type="button"
                id="btn-add-cost-item"
                onClick={handleAddCostItem}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold shadow-xs transition cursor-pointer"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>افزودن ردیف هزینه (+)</span>
              </button>
            </div>

            {/* لیست آیتم‌های هزینه */}
            <div className="space-y-2.5">
              {costItems.map((item, idx) => (
                <div 
                  key={item.id}
                  className="grid grid-cols-1 sm:grid-cols-12 gap-2.5 p-2.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 items-center shadow-xs"
                >
                  <div className="sm:col-span-1 text-center font-mono text-xs font-bold text-slate-400">
                    {idx + 1}#
                  </div>

                  {/* نوع هزینه */}
                  <div className="sm:col-span-5">
                    <input
                      type="text"
                      value={item.costType}
                      onChange={(e) => handleUpdateCostItem(item.id, 'costType', e.target.value)}
                      placeholder="عنوان و سرفصل هزینه (مثال: تامین لوله‌ها)"
                      className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-900 dark:text-white focus:outline-none focus:border-indigo-500 font-medium"
                    />
                  </div>

                  {/* مبلغ برآورد هزینه (میلیون تومان) */}
                  <div className="sm:col-span-3">
                    <div className="relative">
                      <input
                        type="number"
                        min="0"
                        value={item.estimatedAmount}
                        onChange={(e) => handleUpdateCostItem(item.id, 'estimatedAmount', Number(e.target.value))}
                        placeholder="مبلغ"
                        className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-700 rounded-lg pl-2 pr-2 py-1.5 text-xs text-slate-900 dark:text-white font-mono text-center font-bold focus:outline-none focus:border-indigo-500"
                      />
                      <span className="text-[10px] text-slate-400 absolute left-2 top-1/2 -translate-y-1/2 pointer-events-none">م.تومان</span>
                    </div>
                  </div>

                  {/* توضیحات آیتم */}
                  <div className="sm:col-span-2">
                    <input
                      type="text"
                      value={item.description || ''}
                      onChange={(e) => handleUpdateCostItem(item.id, 'description', e.target.value)}
                      placeholder="شرح جزئیات..."
                      className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-700 rounded-lg px-2 py-1.5 text-xs text-slate-600 dark:text-slate-300 focus:outline-none focus:border-indigo-500"
                    />
                  </div>

                  {/* دکمه حذف */}
                  <div className="sm:col-span-1 text-center">
                    <button
                      type="button"
                      onClick={() => handleRemoveCostItem(item.id)}
                      className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 transition cursor-pointer"
                      title="حذف ردیف"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              ))}
            </div>

            {/* جمع نهایی بودجه مصوب کل (BAC) */}
            <div id="field-budgetBAC" className="flex flex-col sm:flex-row items-center justify-between p-3.5 rounded-xl bg-indigo-50/70 dark:bg-indigo-950/40 border border-indigo-200 dark:border-indigo-800/80 gap-3">
              <div className="flex items-center gap-2">
                <DollarSign className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
                <span className="text-xs font-bold text-indigo-950 dark:text-indigo-200">
                  جمع نهایی بودجه کل مصوب پروژه (BAC):
                </span>
              </div>
              <div className="flex items-center gap-2">
                <span className="font-mono text-base font-black text-indigo-700 dark:text-indigo-300">
                  {formatCurrency(totalBudgetBAC)}
                </span>
                <span className="text-xs text-indigo-900/70 dark:text-indigo-300/70 font-semibold">
                  (معادل {toPersianDigits((totalBudgetBAC / 1000).toFixed(1))} میلیارد تومان)
                </span>
              </div>
            </div>
            {errors.budgetBAC && <p className="text-rose-500 text-[10px] font-semibold">{errors.budgetBAC}</p>}
          </div>

          {/* ========================================================================= */}
          {/* بخش ۴.۵: امکان‌سنجی اقتصادی و محاسبه نرخ بازگشت سرمایه (ROI & Payback) */}
          {/* ========================================================================= */}
          <div className="p-4 sm:p-5 rounded-2xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800/80">
            <ProjectROICalculator
              budgetBAC={totalBudgetBAC}
              projectName={name}
              category={category}
              responsibleUnit={responsibleUnit}
              durationDays={calculatedProjectDurationDays}
              costEstimates={costItems}
              value={projectROI}
              onChange={setProjectROI}
            />
          </div>

          {/* ========================================================================= */}
          {/* بخش ۵: فعالیت‌ها و مدت زمان هر فعالیت (قسمت پنجم) */}
          {/* ========================================================================= */}
          <div className="p-4 sm:p-5 rounded-2xl bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800/80 space-y-4">
            <div className="flex items-center justify-between border-b border-slate-200/80 dark:border-slate-800 pb-2">
              <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-bold text-xs sm:text-sm">
                <ListTodo className="w-4 h-4" />
                <span>بخش پنجم: لیست فعالیت‌های کلیدی پروژه و مدت زمان هر فعالیت</span>
              </div>

              {/* دکمه مثبت افزودن فعالیت */}
              <button
                type="button"
                id="btn-add-activity-item"
                onClick={handleAddActivityItem}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold shadow-xs transition cursor-pointer"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>افزودن فعالیت (+)</span>
              </button>
            </div>

            {/* لیست آیتم‌های فعالیت */}
            <div className="space-y-2.5">
              {activityItems.map((act, idx) => (
                <div 
                  key={act.id}
                  className="grid grid-cols-1 sm:grid-cols-12 gap-2.5 p-2.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 items-center shadow-xs"
                >
                  <div className="sm:col-span-1 text-center font-mono text-xs font-bold text-slate-400">
                    {idx + 1}#
                  </div>

                  {/* نام فعالیت */}
                  <div className="sm:col-span-6">
                    <input
                      type="text"
                      value={act.activityName}
                      onChange={(e) => handleUpdateActivityItem(act.id, 'activityName', e.target.value)}
                      placeholder="عنوان و شرح فعالیت پروژه"
                      className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-900 dark:text-white focus:outline-none focus:border-indigo-500 font-medium"
                    />
                  </div>

                  {/* مدت زمان فعالیت به روز */}
                  <div className="sm:col-span-2">
                    <div className="relative">
                      <input
                        type="number"
                        min="1"
                        value={act.durationDays}
                        onChange={(e) => handleUpdateActivityItem(act.id, 'durationDays', Number(e.target.value))}
                        placeholder="مدت"
                        className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-700 rounded-lg pl-2 pr-2 py-1.5 text-xs text-slate-900 dark:text-white font-mono text-center font-bold focus:outline-none focus:border-indigo-500"
                      />
                      <span className="text-[10px] text-slate-400 absolute left-2 top-1/2 -translate-y-1/2 pointer-events-none">روز</span>
                    </div>
                  </div>

                  {/* مسئول اجرا */}
                  <div className="sm:col-span-2">
                    <input
                      type="text"
                      value={act.responsiblePerson || ''}
                      onChange={(e) => handleUpdateActivityItem(act.id, 'responsiblePerson', e.target.value)}
                      placeholder="مسئول پیگیری"
                      className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-700 rounded-lg px-2.5 py-1.5 text-xs text-slate-600 dark:text-slate-300 focus:outline-none focus:border-indigo-500"
                    />
                  </div>

                  {/* دکمه حذف */}
                  <div className="sm:col-span-1 text-center">
                    <button
                      type="button"
                      onClick={() => handleRemoveActivityItem(act.id)}
                      className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 transition cursor-pointer"
                      title="حذف فعالیت"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* باکس جامع خطاهای اعتبارسنجی فرم در صورت وجود */}
          {Object.keys(errors).length > 0 && (
            <div className="p-4 rounded-2xl bg-rose-50 dark:bg-rose-950/50 border-2 border-rose-300 dark:border-rose-800 text-rose-900 dark:text-rose-100 flex items-start gap-3 shadow-lg shadow-rose-500/10">
              <div className="p-2 rounded-xl bg-rose-200 dark:bg-rose-900 text-rose-700 dark:text-rose-200 shrink-0">
                <AlertCircle className="w-5 h-5" />
              </div>
              <div className="text-xs space-y-2 flex-1">
                <div className="flex items-center justify-between">
                  <span className="font-bold text-xs sm:text-sm text-rose-900 dark:text-rose-100">
                    برای ثبت پروژه و ارسال به مدیرعامل، لطفاً موارد زیر را تکمیل فرمایید:
                  </span>
                  <span className="text-[10px] bg-rose-200 dark:bg-rose-900/80 text-rose-800 dark:text-rose-200 px-2.5 py-0.5 rounded-full font-mono font-bold">
                    {toPersianDigits(Object.keys(errors).length)} فیلد نیاز به تکمیل
                  </span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 pt-1">
                  {Object.entries(errors).map(([key, msg]) => (
                    <button
                      key={key}
                      type="button"
                      onClick={() => {
                        const el = document.getElementById(`field-${key}`);
                        if (el) {
                          el.scrollIntoView({ behavior: 'smooth', block: 'center' });
                          setTimeout(() => el.focus(), 150);
                        }
                      }}
                      className="flex items-center gap-2 p-2 rounded-xl bg-white/80 dark:bg-rose-900/40 border border-rose-200 dark:border-rose-800/80 text-rose-800 dark:text-rose-200 hover:bg-rose-100 dark:hover:bg-rose-900/70 transition cursor-pointer text-right group"
                    >
                      <span className="w-2 h-2 rounded-full bg-rose-500 shrink-0 group-hover:scale-125 transition" />
                      <span className="font-semibold text-xs">{msg}</span>
                      <span className="text-[10px] text-rose-600 dark:text-rose-400 mr-auto opacity-75">
                        (کلیک جهت تکمیل)
                      </span>
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* نوار وضعیت اعلان و ارجاع */}
          <div className="p-4 rounded-2xl bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-900/50 flex items-center justify-between text-xs">
            <div className="flex items-center gap-2 text-amber-800 dark:text-amber-300">
              <Clock className="w-4 h-4 shrink-0" />
              <span>
                با کلیک بر روی دکمه زیر، پروژه در لیست پروژه‌ها ثبت شده و وضعیت آن <strong>«در انتظار تایید مدیرعامل»</strong> قرار می‌گیرد.
              </span>
            </div>
          </div>

          {/* Footer Actions */}
          <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-200 dark:border-slate-800">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="px-5 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 text-xs font-semibold text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition cursor-pointer disabled:opacity-50"
            >
              انصراف
            </button>
            <button
              type="submit"
              onClick={(e) => handleSubmit(e)}
              disabled={isSubmitting}
              className="flex items-center gap-2 px-6 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 text-white text-xs font-bold shadow-lg shadow-indigo-600/30 transition cursor-pointer disabled:opacity-75"
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>در حال ثبت و ارسال به مدیرعامل...</span>
                </>
              ) : (
                <>
                  <SendHorizontal className="w-4 h-4" />
                  <span>ثبت و ارسال جهت تایید مدیرعامل</span>
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
